### ISSUE TITLE
API Error Code: 191

### ISSUE THREAD

**Issue by ghost** [myApi/myApi#15] opened 2011-04-21 22:07 UTC
Can't get this to work on my site.  Tried everything.  http://leidabartmess.com/index.php?option=com_k2&view=item&layout=item&id=65&Itemid=72

API Error Code: 191
API Error Description: The specified URL is not owned by the application
Error Message: redirect_uri is not owned by the application.

my page:  http://www.facebook.com/pages/LeidaBartmesscom/102734383127578

my app:  App ID
    167127119980910
API Key
    fe00097f3f972268e4bc69eae302c5bf

Site URL
    http://www.leidabartmess.com/public_html/facebook/facebook-php-sdk-9147097/examples/
Canvas Page
    http://apps.facebook.com/leida_cvp/
Canvas URL
    http://wwwleidabartmess.com/public_html/facebook/facebook-php-sdk-9147097/examples/
Secure Canvas URL
Canvas FBML/iframe
    iframe
Contact Email
    leida@leidabartmess.com
Support Email
    leida@leidabartmess.com
App Description
    canvas page for leidabartmess.com

**Comment by thomaswelton** [comment] 2011-04-21 22:12
Is your base domain set to leidabartmess.com?

**Comment by ghost** [comment] 2011-04-21 23:02
Within my Joomla admin? Or on the Facebook app?

**Comment by thomaswelton** [comment] 2011-04-21 23:11
Facebook app

**Comment by ghost** [comment] 2011-04-23 16:24
Yes.  Changed it.  Still totally out of whack.

-----Original Message-----

**Comment by thomaswelton** [comment] 2011-05-23 20:30
Just to confirm, is this during the initial setup?
Also do you have a site url set in your app settings?

**Comment by thomaswelton** [comment] 2011-05-24 01:44
also try removing the www. from your FB site url and base domain

**Comment by thomaswelton** [comment] 2011-05-25 00:55
Ok so parts of myapi connected with installation and login have been changed in the new version https://github.com/thomaswelton/myApi/zipball/master
Install it and let me know how it goes.

**Comment by joomray** [comment] 2011-05-29 16:21
Hi Thomas
I receive the following error when trying to setup myApi tried all the changes that I can find anywhere on the web but still receive the same error. Setup the web and domain address to suit your suggestions but still the same issue.
Downloaded the link above just to make sure but same issue.
Error - Please check that the details are correct. Exception: 190: Invalid OAuth access token signature.
Setup in FB app
http://myurl.com
domain myurl.com
I know this relates to error code 191 but seems to be of similar nature, cant get past step one.
Cheers
Ray

**Comment by patience-zz** [comment] 2011-05-29 19:08
joomray! I got that error too.. refresh your frontpage the buttons should show up. that is what worked for me.

**Comment by joomray** [comment] 2011-05-29 20:08
Thanks Patience for that tip. Just wish I could have found it sooner instead of wasting time. It should become visible now that it's in this forum. That will help others with the same problem.

**Comment by thomaswelton** [comment] 2011-05-29 21:44
So are all your problems solved joomray? I want to find a way to fix this for everyone.

**Comment by joomray** [comment] 2011-05-30 07:42
Yes thanks Thomas all working. Just don't understand why FB sees my existing group when it has no way from the app side of finding the url. I also opened a page because of the group change but it does not see that so group posts are appearing on the site. Not sure if you have any info on exactly how FB operates with this.

**Comment by thomaswelton** [comment] 2011-05-30 07:52
Ok, well since I posted that comment I made a new version. 1.3.3 you can install that over your existing copy and fixes issues for new installs so try it out also @leidab try out the new version.

If these things are now working for you and you find the free myApi extension useful then please leave an honest review here http://extensions.joomla.org/extensions/social-web/facebook-display/11624 as I feel as though it is the best way to promote myApi and support it's continued growth.

**Comment by joomray** [comment] 2011-05-30 08:14
Hi Thomas
There you go its working like a charm no erroneous error message and I see you added a screen shot for ref purposes. Hope this also solves your 191 error issues.
Thanks for the support will keep you advised if there are any other issues I would like to get this going on a site I look after for an NGO here in SA so my site was more of a testing ground before putting it on their site an possibly causing issues there. Will post a review on Joomla's site for you no prob.

**Comment by thomaswelton** [comment] 2011-05-30 08:17
Great, now just want some confirmation from leidab, if this new update solves your issues can you close this defect with your leidab. Otherwise I have more work to do :)

**Comment by ghost** [comment] 2011-05-30 14:17
I don't have this installed ony new sit yet.

**Comment by thomaswelton** [comment] 2011-05-31 08:52
Ok I've retested and confirmed a fix with other users, but if you reinstall and experience this problem please reopen the issue.

**Closed as completed by thomaswelton** 2011-05-31 08:52 UTC
